<?php

/**
 * BaseTweetSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $label
 * @property string $url
 * @property Doctrine_Collection $Tweet
 * 
 * @method string              getLabel() Returns the current record's "label" value
 * @method string              getUrl()   Returns the current record's "url" value
 * @method Doctrine_Collection getTweet() Returns the current record's "Tweet" collection
 * @method TweetSource         setLabel() Sets the current record's "label" value
 * @method TweetSource         setUrl()   Sets the current record's "url" value
 * @method TweetSource         setTweet() Sets the current record's "Tweet" collection
 * 
 * @package    tweetex
 * @subpackage model
 * @author     Herbert Muehlburger
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTweetSource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tweet_source');
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'web',
             'length' => '255',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));


        $this->index('sourceIndex', array(
             'fields' => 
             array(
              0 => 'label',
              1 => 'url',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tweet', array(
             'local' => 'id',
             'foreign' => 'source_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}