<?php

/**
 * BaseAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $email
 * @property string $token
 * @property boolean $is_active
 * 
 * @method string    getUrl()       Returns the current record's "url" value
 * @method string    getEmail()     Returns the current record's "email" value
 * @method string    getToken()     Returns the current record's "token" value
 * @method boolean   getIsActive()  Returns the current record's "is_active" value
 * @method Affiliate setUrl()       Sets the current record's "url" value
 * @method Affiliate setEmail()     Sets the current record's "email" value
 * @method Affiliate setToken()     Sets the current record's "token" value
 * @method Affiliate setIsActive()  Sets the current record's "is_active" value
 * 
 * @package    grabeeter
 * @subpackage model
 * @author     Herbert Muehlburger
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('affiliate');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}