<?php

/**
 * TweetUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    twitarch
 * @subpackage model
 * @author     Herbert Muehlburger
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class TweetUser extends BaseTweetUser
{
	public function __toString() {
		return $this->getScreenName();
	}
}
