# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

user:
  class:   sfDoctrineRouteCollection
  options: { model: TwitterUser }

tweet:
  class:   sfDoctrineRouteCollection
  options: { model: Tweet }

tweet_show:
  url: /tweet/:id/:text_slug
  class:   sfDoctrineRoute
  options: { model: Tweet, type: object }
  param:   { module: tweet, action: show }
  requirements:
    id: \d+

user_search_tweets:
  url: /tweets
  params:  { module: user, action: searchTweets }
  
# default rules
homepage:
  url:   /
  param: { module: user, action: searchTweets }

default_indecurlx:
  url:   /:module
  param: { action: index }
 
default:
  url:   /:module/:action/*