# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: tweet, action: index }

default_indecurlx:
  url:   /:module
  param: { action: index }
 
default:
  url:   /:module/:action/*