# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

#########################################
# Help Routes
##
help_faq:
  url:    /frequently-asked-questions.:sf_format
  param:  { module: help, action: faq, sf_format: html }
  
help_userguide:
  url:    /userguide.:sf_format
  param:  { module: help, action: help, sf_format: html }
  
help_api:
  url:    /developers.:sf_format
  param:  { module: help, action: api, sf_format: html }

#########################################
# Api Routes
##
api_tweets:
  url:     /api/tweets/:screen_name.:sf_format
  class:   sfDoctrineRoute
  param:   { module: api, action: list, sf_format: xml }
  options: { model: Tweet, type: list, method: getForUsername }
  requirements:
    sf_format: (?:xml|json|yaml)
    sf_method: get

#########################################
# User Routes
##
user:
  class:   sfDoctrineRouteCollection
  options: { model: TweetUser }

user_show:
  url:     /:screen_name/profile
  class:    sfDoctrineRoute
  options: { model: TweetUser, type: object }
  params:  { module: user, action: show }
  requires:
    sf_method: get
    
#########################################
# Registration Routes
##
registration:
  url:     /registration
  param:   { module: registration, action: index }
  
registration_thankyou:
  url:    /registration/thankyou
  param:  { module: registration, action: thankyou }
    
#########################################
# Source Routes
##
source:
  class:   sfDoctrineRouteCollection
  options: { model: TweetSource }

#########################################
# Tweet Routes
##  
tweet_user_tweets:
  url:     /tweets/:screen_name/:page
  class:    sfDoctrineRoute
  options: { model: Tweet, type: object }
  params:  { module: tweet, action: index, page: 1 }
  requires:
    sf_method: get
  
tweet_show:
  url:     /tweet/:id/:text_slug
  class:    sfDoctrineRoute
  options: { model: Tweet, type: object }
  params:  { module: tweet, action: show }
  requires:
    sf_method: get

tweet_search:
  url:    /search
  param:  { module: tweet, action: search }
  requirements:
    sf_method: get

tweet:
  class:   sfDoctrineRouteCollection
  options: { model: Tweet }
  
#########################################
# Geolocation Routes
##
geolocation:
  class:   sfDoctrineRouteCollection
  options: { model: TweetGeoLocation }

# default rules
homepage:
  url:   /
  param: { module: help, action: index }

#default_index:
#  url:   /:module
#  param: { action: index }
# 
#default:
#  url:   /:module/:action/*