# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

#########################################
# Api Routes
##
api_tweets:
  url:     /api/tweets/:username.:sf_format
  class:   sfDoctrineRoute
  param:   { module: api, action: list, sf_format: xml }
  options: { model: Tweet, type: list, method: getForUsername }
  requirements:
    sf_format: (?:xml|json|yaml)
    sf_method: get
    
api_search:
  url:    /api/search/:q.:sf_format
  param:  { module: api, action: search, sf_format: xml }
  requirements:
    sf_format: (?:xml|json|yaml)
    sf_method: get

#########################################
# User Routes
##
user:
  class:   sfDoctrineRouteCollection
  options: { model: TweetUser }

user_show:
  url:     /:screen_name/profile
  class:    sfDoctrineRoute
  options: { model: TweetUser, type: object }
  params:  { module: user, action: show }
  requires:
    sf_method: get
    
#########################################
# Source Routes
##
source:
  class:   sfDoctrineRouteCollection
  options: { model: TweetSource }

#########################################
# Tweet Routes
##  
tweet_user_tweets:
  url:     /:screen_name/tweets/:page
  class:    sfDoctrineRoute
  options: { model: Tweet, type: object }
  params:  { module: tweet, action: index, page: 1 }
  requires:
    sf_method: get
  
tweet_show:
  url:     /tweet/:id/:text_slug
  class:    sfDoctrineRoute
  options: { model: Tweet, type: object }
  params:  { module: tweet, action: show }
  requires:
    sf_method: get

tweet_search:
  url:    /search
  param:  { module: tweet, action: search }
  requirements:
    sf_method: get

tweet:
  class:   sfDoctrineRouteCollection
  options: { model: Tweet }
  
#########################################
# Geolocation Routes
##
geolocation:
  class:   sfDoctrineRouteCollection
  options: { model: TweetGeoLocation }

# default rules
homepage:
  url:   /
  param: { module: tweet, action: index }

#default_index:
#  url:   /:module
#  param: { action: index }
# 
#default:
#  url:   /:module/:action/*