# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

user:
  class:   sfDoctrineRouteCollection
  options: { model: TwitterUser }

tweet:
  class:   sfDoctrineRouteCollection
  options: { model: Tweet }

# default rules
homepage:
  url:   /
  param: { module: tweet, action: index }

 
default_index:
  url:   /:module
  param: { action: index }
 
default:
  url:   /:module/:action/*