# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
 
  metas:
    title:        Grabeeter - Grab and Search your Tweets
    description:  Grabeeter - Grab and Search your Tweets
    keywords:     grabeeter, tweet, twitter, export, save, backup, service, search, grab
    language:     en
    robots:       index, follow
 
  stylesheets:    [reset.css, 960.css, main.css, default.css, text.css]
 
  javascripts:    []
 
  has_layout:     true
  layout:         layout