generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Tweet
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tweet
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        user_id:   { label: Twitter User, help: Creator of this tweet. }
        source_id: { label: Source, help: The tweet was created using this application. }
        geolocation:
      list:
        title:    Tweet Management
        display:  [=text]
        max_per_page: 100
      filter:  ~
      form:    ~
      edit:
        title: Editing Tweet: "%%text%%"
      new:     ~
