Tweet:
  actAs: { Timestampable: ~ }
  columns:
    user_id: { type: integer, notnull: true }
    text:    { type: string(140), notnull: true }
  relations:
    TwitterUser: { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: Tweets }

TwitterUser:
  actAs: { Timestampable: ~ }
  columns:
    name:  { type: string(255), notnull: true, unique: true }