Tweet:
  actAs: { Timestampable: ~ }
  columns:
    user_id:
      type: integer
      notnull: true
    source_id:
      type: integer
      notnull: true
    geolocation_id:
      type: integer
    in_reply_to_user_id:
      type: integer(12)
    in_reply_to_status_id:
      type: integer(20)
    tweet_created_at:
      type: timestamp 
      notnull: true
    tweet_twitter_id:
      type: integer
      notnull: true
      default: 0
    statuses_count:
      type: integer
      notnull: true
      default: 0
    text:                 
      type: string(140)
      notnull: true
  relations:
    TweetUser:  { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: Tweets }
    TweetSource:  { onDelete: CASCADE, local: source_id, foreign: id, foreignAlias: Tweets } 
    TweetGeoLocation:  { onDelete: CASCADE, local: geolocation_id, foreign: id, foreignAlias: Tweets }

TweetUser:
  actAs: { Timestampable: ~ }
  columns:
    name:
      type: string(255)
    screen_name: 
      type: string(15)
      notnull: true
    twitter_user_id:
      type: integer
      notnull: true
    description:
      type: string(255)
    followers_count:
      type: integer
      notnull: true
      default: 0
    statuses_count:
      type: integer
      notnull: true
      default: 0
    screen_name:
      type: string(15)
      notnull: true
    url:
      type: string(255)
    friends_count:
      type: integer
      notnull: true
      default: 0
    geo_enabled:
      type: boolean
      notnull: true
      default: false
    twitter_created_at:
      type: timestamp
      notnull: true
    time_zone:
      type: string(255)
    location:
      type: string(255)
    lang:
      type: string(10)
    utc_offset:
      type: integer
    profile_image_url:
      type: string(255)
      notnull: true
        
TweetSource:
  actAs: { Timestampable: ~ }
  columns:
    label:
      type: string(255)
      notnull: true
      default: web
    url:
      type: string(255)

TweetGeoLocation:
  actAs: { Timestampable: ~ }
  columns:
    latitude:
      type: float(9,6)
      notnull: true
      default: 0
    longitude:
      type: float(9,6)
      notnull: true
      default: 0